# Generated by Django 5.0.2 on 2024-03-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='progress',
        ),
    ]
