# Generated by Django 5.0.2 on 2024-03-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapp', '0002_remove_tasks_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='icon',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
