# Generated by Django 5.0.2 on 2024-03-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapp', '0003_tasks_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='description',
            new_name='text',
        ),
    ]
